#![allow(clippy::useless_conversion)] // Generated by PyO3's #[pyfn] wrappers.

//! NucXplore: High-performance histopathology feature extraction
//!
//! This library provides fast, GPU-accelerated feature extraction for histopathology images.
//! It extracts morphological, texture, color, and spatial features from nucleus segmentations.

use ndarray::{s, Array2, Array3, ArrayView2, ArrayView3};
use pyo3::prelude::*;
use std::collections::{BTreeMap, HashMap};
use std::path::{Path, PathBuf};

mod core;
pub mod features;
pub mod gpu;
pub mod io;
pub mod stain_norm;

// Re-export core types
pub use core::{
    extract_patch, init_logging, rgb_to_grayscale, FeatureConfig, FeatureVector, FeaturizerError,
    ImagePatch, NucleusMask, Result,
};
pub use gpu::is_gpu_available;

const PATCH_PADDING: usize = 10;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum FeatureSchema {
    Legacy,
    Dual,
    V2,
}

impl FeatureSchema {
    fn parse(value: &str) -> std::result::Result<Self, String> {
        match value.to_ascii_lowercase().as_str() {
            "legacy" => Ok(Self::Legacy),
            "dual" => Ok(Self::Dual),
            "v2" => Ok(Self::V2),
            _ => Err(format!(
                "feature_schema must be one of legacy, dual, or v2; got {value:?}"
            )),
        }
    }
}

#[derive(Clone, Debug)]
pub struct CropSaveRecord {
    pub nucleus_id: u32,
    pub bbox: (usize, usize, usize, usize),
    pub path: PathBuf,
}

#[derive(Clone, Copy)]
struct BoundingBox {
    min_row: usize,
    max_row: usize,
    min_col: usize,
    max_col: usize,
}

impl BoundingBox {
    fn new(row: usize, col: usize) -> Self {
        Self {
            min_row: row,
            max_row: row,
            min_col: col,
            max_col: col,
        }
    }

    fn include(&mut self, row: usize, col: usize) {
        self.min_row = self.min_row.min(row);
        self.max_row = self.max_row.max(row);
        self.min_col = self.min_col.min(col);
        self.max_col = self.max_col.max(col);
    }

    fn padded(self, image_h: usize, image_w: usize, padding: usize) -> Self {
        Self {
            min_row: self.min_row.saturating_sub(padding),
            max_row: (self.max_row + padding).min(image_h - 1),
            min_col: self.min_col.saturating_sub(padding),
            max_col: (self.max_col + padding).min(image_w - 1),
        }
    }
}

fn feature_error(feature: String, err: FeaturizerError) -> FeaturizerError {
    FeaturizerError::FeatureComputationFailed {
        feature,
        reason: err.to_string(),
    }
}

fn morphology_features_with_offset(
    mask: &ArrayView2<'_, bool>,
    row_offset: usize,
    col_offset: usize,
) -> Result<HashMap<String, f64>> {
    let tuples = features::morphology::calculate_morphological_features(mask)?;
    let mut feature_map = HashMap::with_capacity(tuples.len());
    for (key, value) in tuples {
        let adjusted = match key.as_str() {
            "centroid_row" => value + row_offset as f64,
            "centroid_col" => value + col_offset as f64,
            _ => value,
        };
        feature_map.insert(key, adjusted);
    }
    Ok(feature_map)
}

fn calculate_hu_moments(mask: &ArrayView2<'_, bool>, area: f64) -> Result<HashMap<String, f64>> {
    let mut out: HashMap<String, f64> = (1..=7).map(|i| (format!("hu_moment_{i}"), 0.0)).collect();

    if area <= 10.0 {
        return Ok(out);
    }
    if mask.iter().filter(|&&v| v).count() <= 5 {
        return Ok(out);
    }

    // Compute Hu moments with the correct raw -> central -> normalized -> Hu
    // pipeline (moments::calculate_hu_moments).
    //
    // Previous code deliberately mirrored the Python reference call pattern
    // `moments_normalized(binary_mask, order=3)`, which treats image pixels as
    // if they were central moments. On modern scikit-image that call divides
    // by `image[0, 0]` (0 for a padded nucleus) -> NaN for all seven moments,
    // so every hu_moment_* feature collapsed to 0.0. See audit finding A04.
    let hu = features::moments::calculate_hu_moments(mask)?;
    for (key, value) in hu.iter() {
        out.insert(
            key.clone(),
            if value.is_finite() && value.abs() < 1e10 {
                *value
            } else {
                0.0
            },
        );
    }
    Ok(out)
}

fn build_instance_regions(
    instance_map: &ArrayView2<'_, u32>,
) -> Vec<(u32, BoundingBox, Array2<bool>)> {
    let mut bboxes: BTreeMap<u32, BoundingBox> = BTreeMap::new();
    for ((row, col), &instance_id) in instance_map.indexed_iter() {
        if instance_id == 0 {
            continue;
        }
        bboxes
            .entry(instance_id)
            .and_modify(|bbox| bbox.include(row, col))
            .or_insert_with(|| BoundingBox::new(row, col));
    }

    let mut out = Vec::with_capacity(bboxes.len());
    for (instance_id, bbox) in bboxes {
        let crop_h = bbox.max_row - bbox.min_row + 1;
        let crop_w = bbox.max_col - bbox.min_col + 1;
        let mut tight_mask = Array2::<bool>::from_elem((crop_h, crop_w), false);
        for row in bbox.min_row..=bbox.max_row {
            for col in bbox.min_col..=bbox.max_col {
                if instance_map[[row, col]] == instance_id {
                    tight_mask[[row - bbox.min_row, col - bbox.min_col]] = true;
                }
            }
        }
        out.push((instance_id, bbox, tight_mask));
    }
    out
}

fn build_patch_mask(
    instance_map: &ArrayView2<'_, u32>,
    instance_id: u32,
    bounds: BoundingBox,
) -> Array2<bool> {
    let patch_h = bounds.max_row - bounds.min_row + 1;
    let patch_w = bounds.max_col - bounds.min_col + 1;
    let mut mask = Array2::<bool>::from_elem((patch_h, patch_w), false);
    for row in bounds.min_row..=bounds.max_row {
        for col in bounds.min_col..=bounds.max_col {
            if instance_map[[row, col]] == instance_id {
                mask[[row - bounds.min_row, col - bounds.min_col]] = true;
            }
        }
    }
    mask
}

fn crop_rgb_patch(image: &ArrayView3<'_, u8>, bounds: BoundingBox) -> Array3<u8> {
    image
        .slice(s![
            bounds.min_row..=bounds.max_row,
            bounds.min_col..=bounds.max_col,
            ..
        ])
        .to_owned()
}

fn apply_mask_to_rgb_patch(rgb_patch: &mut Array3<u8>, mask_patch: &ArrayView2<'_, bool>) {
    for ((row, col), &keep) in mask_patch.indexed_iter() {
        if !keep {
            rgb_patch[[row, col, 0]] = 0;
            rgb_patch[[row, col, 1]] = 0;
            rgb_patch[[row, col, 2]] = 0;
        }
    }
}

fn to_f32_grayscale(gray_u8: &Array2<u8>) -> Array2<f32> {
    gray_u8.mapv(|v| v as f32)
}

fn canonical_feature_name(key: &str) -> String {
    match key {
        "ccsm_mean_dist_to_edge" => "ccsm_mean_dist_to_boundary".to_string(),
        "ccsm_texture_contrast" => "ccsm_contrast".to_string(),
        "ccsm_texture_correlation" => "ccsm_correlation".to_string(),
        "ccsm_texture_energy" => "ccsm_energy".to_string(),
        "ccsm_texture_homogeneity" => "ccsm_homogeneity".to_string(),
        _ => key.to_string(),
    }
}

fn extend_legacy_patch_features(
    target: &mut HashMap<String, f64>,
    pre_features: &HashMap<String, f64>,
    post_features: &HashMap<String, f64>,
) {
    for (key, value) in pre_features {
        let canonical = canonical_feature_name(key);
        target.insert(format!("pre_norm_{canonical}"), *value);
    }
    for (key, value) in post_features {
        let canonical = canonical_feature_name(key);
        target.insert(format!("post_norm_{canonical}"), *value);
    }
}

fn compute_pre_post_patch_features(
    pre_rgb_patch: &ArrayView3<'_, u8>,
    post_rgb_patch: &ArrayView3<'_, u8>,
    mask_patch: &ArrayView2<'_, bool>,
    use_gpu: bool,
) -> Result<(HashMap<String, f64>, HashMap<String, f64>)> {
    let pre = compute_patch_features(pre_rgb_patch, mask_patch, use_gpu)?;
    let post = compute_patch_features(post_rgb_patch, mask_patch, use_gpu)?;
    Ok((pre, post))
}

/// Algorithm: masked patch feature extraction for raw and normalized RGB data.
///
/// Time complexity: O(P + F), where P is the padded patch pixel count and F is
/// the number of emitted patch features. Space complexity: O(P + F) for
/// grayscale intermediates and the feature map. The caller invokes this once
/// for the raw patch and once for the corresponding tile-normalized patch.
fn compute_patch_features(
    rgb_patch: &ArrayView3<'_, u8>,
    mask_patch: &ArrayView2<'_, bool>,
    use_gpu: bool,
) -> Result<HashMap<String, f64>> {
    let gray_u8 = rgb_to_grayscale(rgb_patch);
    let gray_f32 = to_f32_grayscale(&gray_u8);
    let mut features_map = HashMap::new();

    features_map.extend(features::intensity::calculate_intensity_features(
        &gray_f32.view(),
        mask_patch,
    )?);
    features_map.extend(features::glcm::calculate_glcm_features_with_gpu(
        &gray_f32.view(),
        mask_patch,
        use_gpu,
    )?);
    features_map.extend(features::lbp::calculate_lbp_features(
        &gray_f32.view(),
        mask_patch,
    )?);
    features_map.extend(features::he_color::calculate_he_color_features(
        rgb_patch, mask_patch,
    )?);
    features_map.extend(features::hog::calculate_hog_features(
        &gray_f32.view(),
        mask_patch,
        use_gpu,
    )?);
    features_map.extend(features::ccsm::calculate_ccsm_features_with_gpu(
        &gray_f32.view(),
        mask_patch,
        use_gpu,
    )?);
    Ok(features_map)
}

fn add_v2_features(
    target: &mut HashMap<String, f64>,
    rgb_patch: &ArrayView3<'_, u8>,
    mask_patch: &ArrayView2<'_, bool>,
    legacy_patch: &HashMap<String, f64>,
) -> Result<()> {
    // Copy unaffected, unique patch features first. Corrected implementations
    // below overwrite only the feature families with identified defects.
    for (key, value) in legacy_patch {
        target.insert(format!("v2_{}", canonical_feature_name(key)), *value);
    }
    for (key, value) in features::v2::hu(mask_patch) {
        target.insert(format!("v2_{key}"), value);
    }
    let (dimension, r2, scales) = features::v2::box_counting(mask_patch);
    target.insert("v2_fractal_dimension".to_string(), dimension);
    target.insert("v2_fractal_dimension_r2".to_string(), r2);
    target.insert("v2_fractal_dimension_scales".to_string(), scales);
    for (index, value) in features::v2::fourier(mask_patch).iter().enumerate() {
        target.insert(format!("v2_fourier_descriptor_{}", index + 1), *value);
    }
    let gray = to_f32_grayscale(&rgb_to_grayscale(rgb_patch));
    for map in [
        features::v2::glcm(&gray.view(), mask_patch)?,
        features::v2::he(rgb_patch, mask_patch)?,
        features::v2::gradients(&gray.view(), mask_patch),
        features::ccsm::calculate_ccsm_features_v2(&gray.view(), mask_patch)?,
    ] {
        for (key, value) in map {
            target.insert(format!("v2_{}", canonical_feature_name(&key)), value);
        }
    }
    Ok(())
}

fn finalize_schema(map: &mut HashMap<String, f64>, schema: FeatureSchema) {
    if schema == FeatureSchema::Legacy {
        return;
    }
    let legacy_snapshot: Vec<(String, f64)> = map
        .iter()
        .filter(|(key, _)| {
            key.as_str() != "nucleus_id"
                && !key.starts_with("pre_norm_")
                && !key.starts_with("post_norm_")
                && !key.starts_with("v2_")
        })
        .map(|(key, value)| (key.clone(), *value))
        .collect();
    for (key, value) in legacy_snapshot {
        map.entry(format!("v2_{key}")).or_insert(value);
    }
    if schema == FeatureSchema::V2 {
        map.retain(|key, _| key == "nucleus_id" || key.starts_with("v2_"));
    }
}

fn add_nearest_neighbor_distances(feature_maps: &mut [HashMap<String, f64>]) {
    let centroids: Vec<(f64, f64)> = feature_maps
        .iter()
        .map(|map| {
            (
                map.get("centroid_row").copied().unwrap_or(0.0),
                map.get("centroid_col").copied().unwrap_or(0.0),
            )
        })
        .collect();

    for (idx, map) in feature_maps.iter_mut().enumerate() {
        let distance = if centroids.len() <= 1 {
            0.0
        } else {
            let (cy, cx) = centroids[idx];
            let mut min_dist = f64::INFINITY;
            for (j, &(oy, ox)) in centroids.iter().enumerate() {
                if j == idx {
                    continue;
                }
                let d = ((cy - oy).powi(2) + (cx - ox).powi(2)).sqrt();
                if d < min_dist {
                    min_dist = d;
                }
            }
            if min_dist.is_finite() {
                min_dist
            } else {
                0.0
            }
        };
        map.insert("distance_to_nearest_neighbor".to_string(), distance);
    }
}

pub fn save_cropped_nuclei_from_instance_map(
    image: &ArrayView3<'_, u8>,
    instance_map: &ArrayView2<'_, u32>,
    output_dir: &Path,
    padding: usize,
) -> Result<Vec<CropSaveRecord>> {
    let (image_h, image_w, _) = image.dim();
    let map_shape = instance_map.dim();
    if map_shape.0 != image_h || map_shape.1 != image_w {
        return Err(FeaturizerError::InvalidDimensions {
            expected: format!("({}, {})", image_h, image_w),
            got: format!("({}, {})", map_shape.0, map_shape.1),
        });
    }

    let mut records = Vec::new();

    for (instance_id, bbox, _tight_mask) in build_instance_regions(instance_map) {
        let patch_bounds = bbox.padded(image_h, image_w, padding);
        let patch_mask = build_patch_mask(instance_map, instance_id, patch_bounds);
        let filename = format!("nucleus_{instance_id:04}.png");
        let mut patch = crop_rgb_patch(image, patch_bounds);
        apply_mask_to_rgb_patch(&mut patch, &patch_mask.view());
        let path = output_dir.join("nuclei").join(&filename);
        io::image::save_rgb_image(&path, &patch.view())?;

        records.push(CropSaveRecord {
            nucleus_id: instance_id,
            bbox: (
                patch_bounds.min_row,
                patch_bounds.min_col,
                patch_bounds.max_row,
                patch_bounds.max_col,
            ),
            path,
        });
    }

    Ok(records)
}

fn extract_all_features_from_instance_map(
    image: &ArrayView3<'_, u8>,
    instance_map: &ArrayView2<'_, u32>,
    use_gpu: bool,
    schema: FeatureSchema,
) -> Result<Vec<HashMap<String, f64>>> {
    let (image_h, image_w, _) = image.dim();
    let regions = build_instance_regions(instance_map);
    if regions.is_empty() {
        return Ok(Vec::new());
    }
    let normalized_image = stain_norm::normalize_staining_default(image)
        .map_err(|err| feature_error("vahadane(tile)".to_string(), err))?;
    let mut outputs = Vec::with_capacity(regions.len());

    for (instance_id, bbox, _tight_mask) in regions {
        let patch_bounds = bbox.padded(image_h, image_w, PATCH_PADDING);
        let patch_mask = build_patch_mask(instance_map, instance_id, patch_bounds);

        let mut feature_map = morphology_features_with_offset(
            &patch_mask.view(),
            patch_bounds.min_row,
            patch_bounds.min_col,
        )
        .map_err(|err| feature_error(format!("morphology(instance_id={instance_id})"), err))?;
        feature_map.insert("nucleus_id".to_string(), instance_id as f64);

        let area = feature_map.get("area").copied().unwrap_or(0.0);
        let hu = calculate_hu_moments(&patch_mask.view(), area)
            .map_err(|err| feature_error(format!("hu_moments(instance_id={instance_id})"), err))?;
        feature_map.extend(hu);

        let rgb_patch = crop_rgb_patch(image, patch_bounds);
        let normalized_patch = crop_rgb_patch(&normalized_image.view(), patch_bounds);
        let (patch_features, post_patch_features) = compute_pre_post_patch_features(
            &rgb_patch.view(),
            &normalized_patch.view(),
            &patch_mask.view(),
            use_gpu,
        )
        .map_err(|err| feature_error(format!("patch(instance_id={instance_id})"), err))?;
        extend_legacy_patch_features(&mut feature_map, &patch_features, &post_patch_features);
        if schema != FeatureSchema::Legacy {
            add_v2_features(
                &mut feature_map,
                &rgb_patch.view(),
                &patch_mask.view(),
                &patch_features,
            )
            .map_err(|err| feature_error(format!("v2(instance_id={instance_id})"), err))?;
        }

        let advanced_shape = features::shape::calculate_advanced_shape_features(&patch_mask.view())
            .map_err(|err| {
                feature_error(format!("advanced_shape(instance_id={instance_id})"), err)
            })?;
        feature_map.extend(advanced_shape);
        let neis = features::neis::calculate_neis_features(&patch_mask.view())
            .map_err(|err| feature_error(format!("neis(instance_id={instance_id})"), err))?;
        feature_map.extend(neis);

        outputs.push(feature_map);
    }

    add_nearest_neighbor_distances(&mut outputs);
    for map in &mut outputs {
        finalize_schema(map, schema);
    }
    Ok(outputs)
}

fn feature_maps_to_pylist<'py>(
    py: Python<'py>,
    feature_maps: Vec<HashMap<String, f64>>,
) -> PyResult<Bound<'py, pyo3::types::PyList>> {
    use pyo3::types::{PyDict, PyList};

    let py_results = PyList::empty_bound(py);
    for feature_map in feature_maps {
        let py_dict = PyDict::new_bound(py);
        for (key, value) in feature_map {
            py_dict.set_item(key, value)?;
        }
        py_results.append(py_dict)?;
    }
    Ok(py_results)
}

fn expand_user_path(raw_path: &str) -> PathBuf {
    if let Some(stripped) = raw_path.strip_prefix("~/") {
        if let Ok(home) = std::env::var("HOME") {
            return Path::new(&home).join(stripped);
        }
    }
    PathBuf::from(raw_path)
}

/// Python module initialization
#[pymodule]
fn _core(m: &Bound<'_, PyModule>) -> PyResult<()> {
    // Initialize logging
    init_logging();

    // Add version info
    m.add("__version__", env!("CARGO_PKG_VERSION"))?;

    // Add GPU availability check
    #[pyfn(m)]
    #[allow(clippy::useless_conversion)]
    fn check_gpu() -> bool {
        is_gpu_available()
    }

    #[pyfn(m)]
    #[allow(clippy::useless_conversion)]
    fn get_gpu_device_count() -> usize {
        if is_gpu_available() {
            1
        } else {
            0
        }
    }

    #[pyfn(m)]
    #[allow(clippy::useless_conversion)]
    #[pyo3(signature = (image, masks, use_gpu=None, feature_schema="legacy"))]
    fn extract_features<'py>(
        py: Python<'py>,
        image: &Bound<'py, PyAny>,
        masks: &Bound<'py, PyAny>,
        use_gpu: Option<bool>,
        feature_schema: &str,
    ) -> PyResult<Bound<'py, pyo3::types::PyList>> {
        use numpy::{PyReadonlyArray2, PyReadonlyArray3, PyUntypedArrayMethods};
        use pyo3::exceptions::PyTypeError;
        use pyo3::types::PyList;

        let image_arr: PyReadonlyArray3<u8> = image.extract()?;
        let image_shape = image_arr.shape();
        core::numpy_interop::validate_image_shape(image_shape).map_err(pyo3::PyErr::from)?;
        let image_view = image_arr.as_array();

        let use_gpu = use_gpu.unwrap_or(false);
        let schema = FeatureSchema::parse(feature_schema)
            .map_err(pyo3::exceptions::PyValueError::new_err)?;
        if use_gpu && !is_gpu_available() {
            return Err(pyo3::PyErr::from(FeaturizerError::CudaError(
                "GPU requested but no compatible WGPU adapter is available".to_string(),
            )));
        }

        let mut results: Vec<HashMap<String, f64>> = if let Ok(instance_map_arr) =
            masks.extract::<PyReadonlyArray2<u32>>()
        {
            core::numpy_interop::validate_mask_shape(instance_map_arr.shape())
                .map_err(pyo3::PyErr::from)?;
            let map_shape = instance_map_arr.shape();
            if map_shape[0] != image_shape[0] || map_shape[1] != image_shape[1] {
                return Err(pyo3::PyErr::from(FeaturizerError::InvalidDimensions {
                    expected: format!("({}, {})", image_shape[0], image_shape[1]),
                    got: format!("({}, {})", map_shape[0], map_shape[1]),
                }));
            }
            extract_all_features_from_instance_map(
                &image_view,
                &instance_map_arr.as_array(),
                use_gpu,
                schema,
            )
            .map_err(pyo3::PyErr::from)?
        } else {
            let normalized_image = stain_norm::normalize_staining_default(&image_view)
                .map_err(|err| feature_error("vahadane(tile)".to_string(), err))
                .map_err(pyo3::PyErr::from)?;
            let masks_list = masks.downcast::<PyList>().map_err(|_| {
                PyTypeError::new_err(
                    "masks must be either a 2D numpy uint32 instance map or a list of 2D numpy bool arrays",
                )
            })?;

            let mut out = Vec::with_capacity(masks_list.len());

            for (idx, mask_obj) in masks_list.iter().enumerate() {
                let mask_arr: PyReadonlyArray2<bool> = mask_obj.extract().map_err(|err| {
                    PyTypeError::new_err(format!(
                        "masks[{idx}] must be a 2D numpy bool array: {err}"
                    ))
                })?;
                core::numpy_interop::validate_mask_shape(mask_arr.shape())
                    .map_err(pyo3::PyErr::from)?;
                let (mh, mw) = (mask_arr.shape()[0], mask_arr.shape()[1]);
                if mh != image_shape[0] || mw != image_shape[1] {
                    return Err(pyo3::PyErr::from(FeaturizerError::InvalidDimensions {
                        expected: format!("({}, {})", image_shape[0], image_shape[1]),
                        got: format!("({}, {})", mh, mw),
                    }));
                }

                let mask_view = mask_arr.as_array();
                let mut feature_map = morphology_features_with_offset(&mask_view, 0, 0)
                    .map_err(|err| feature_error(format!("morphology(mask_index={idx})"), err))
                    .map_err(pyo3::PyErr::from)?;
                feature_map.insert("nucleus_id".to_string(), (idx + 1) as f64);
                let area = feature_map.get("area").copied().unwrap_or(0.0);
                feature_map.extend(
                    calculate_hu_moments(&mask_view, area)
                        .map_err(|err| feature_error(format!("hu_moments(mask_index={idx})"), err))
                        .map_err(pyo3::PyErr::from)?,
                );

                let (rgb_patch, _, patch_mask) =
                    extract_patch(&image_view, &mask_view, PATCH_PADDING)
                        .map_err(|err| feature_error(format!("patch(mask_index={idx})"), err))
                        .map_err(pyo3::PyErr::from)?;
                let (normalized_patch, _, _) =
                    extract_patch(&normalized_image.view(), &mask_view, PATCH_PADDING)
                        .map_err(|err| {
                            feature_error(format!("normalized_patch(mask_index={idx})"), err)
                        })
                        .map_err(pyo3::PyErr::from)?;
                let (patch_features, post_patch_features) = compute_pre_post_patch_features(
                    &rgb_patch.view(),
                    &normalized_patch.view(),
                    &patch_mask.view(),
                    use_gpu,
                )
                .map_err(|err| feature_error(format!("patch(mask_index={idx})"), err))
                .map_err(pyo3::PyErr::from)?;
                extend_legacy_patch_features(
                    &mut feature_map,
                    &patch_features,
                    &post_patch_features,
                );
                if schema != FeatureSchema::Legacy {
                    add_v2_features(
                        &mut feature_map,
                        &rgb_patch.view(),
                        &patch_mask.view(),
                        &patch_features,
                    )
                    .map_err(|err| feature_error(format!("v2(mask_index={idx})"), err))
                    .map_err(pyo3::PyErr::from)?;
                }
                feature_map.extend(
                    features::shape::calculate_advanced_shape_features(&patch_mask.view())
                        .map_err(|err| {
                            feature_error(format!("advanced_shape(mask_index={idx})"), err)
                        })
                        .map_err(pyo3::PyErr::from)?,
                );
                feature_map.extend(
                    features::neis::calculate_neis_features(&patch_mask.view())
                        .map_err(|err| feature_error(format!("neis(mask_index={idx})"), err))
                        .map_err(pyo3::PyErr::from)?,
                );
                out.push(feature_map);
            }
            out
        };

        add_nearest_neighbor_distances(&mut results);
        for map in &mut results {
            finalize_schema(map, schema);
        }

        feature_maps_to_pylist(py, results)
    }

    #[pyfn(m)]
    #[pyo3(signature = (image_path, mat_path, mat_key=None, use_gpu=None, feature_schema="legacy"))]
    fn extract_features_from_files<'py>(
        py: Python<'py>,
        image_path: &str,
        mat_path: &str,
        mat_key: Option<&str>,
        use_gpu: Option<bool>,
        feature_schema: &str,
    ) -> PyResult<Bound<'py, pyo3::types::PyList>> {
        let use_gpu = use_gpu.unwrap_or(false);
        let schema = FeatureSchema::parse(feature_schema)
            .map_err(pyo3::exceptions::PyValueError::new_err)?;
        if use_gpu && !is_gpu_available() {
            return Err(pyo3::PyErr::from(FeaturizerError::CudaError(
                "GPU requested but no compatible WGPU adapter is available".to_string(),
            )));
        }

        let image_path = expand_user_path(image_path);
        let mat_path = expand_user_path(mat_path);

        let image = io::image::load_rgb_image(&image_path).map_err(pyo3::PyErr::from)?;
        let (instance_map, _detected_key) =
            io::mat::load_instance_map(&mat_path, mat_key).map_err(pyo3::PyErr::from)?;

        if image.dim().0 != instance_map.dim().0 || image.dim().1 != instance_map.dim().1 {
            return Err(pyo3::PyErr::from(FeaturizerError::InvalidDimensions {
                expected: format!("({}, {})", image.dim().0, image.dim().1),
                got: format!("({}, {})", instance_map.dim().0, instance_map.dim().1),
            }));
        }

        let results = extract_all_features_from_instance_map(
            &image.view(),
            &instance_map.view(),
            use_gpu,
            schema,
        )
        .map_err(pyo3::PyErr::from)?;
        feature_maps_to_pylist(py, results)
    }

    #[pyfn(m)]
    #[pyo3(signature = (image_path, mat_path, output_dir, mat_key=None, padding=10))]
    fn save_cropped_nuclei_from_files<'py>(
        py: Python<'py>,
        image_path: &str,
        mat_path: &str,
        output_dir: &str,
        mat_key: Option<&str>,
        padding: usize,
    ) -> PyResult<Bound<'py, pyo3::types::PyList>> {
        use pyo3::types::{PyDict, PyList};

        let image_path = expand_user_path(image_path);
        let mat_path = expand_user_path(mat_path);
        let output_dir = expand_user_path(output_dir);

        let image = io::image::load_rgb_image(&image_path).map_err(pyo3::PyErr::from)?;
        let (instance_map, _detected_key) =
            io::mat::load_instance_map(&mat_path, mat_key).map_err(pyo3::PyErr::from)?;
        let records = save_cropped_nuclei_from_instance_map(
            &image.view(),
            &instance_map.view(),
            &output_dir,
            padding,
        )
        .map_err(pyo3::PyErr::from)?;

        let out = PyList::empty_bound(py);
        for record in records {
            let dict = PyDict::new_bound(py);
            dict.set_item("nucleus_id", record.nucleus_id)?;
            dict.set_item("bbox", record.bbox)?;
            dict.set_item("path", record.path.to_string_lossy().to_string())?;
            out.append(dict)?;
        }
        Ok(out)
    }

    Ok(())
}

#[cfg(test)]
mod hu_moments_regression_tests {
    use super::*;

    fn ellipse_mask(
        h: usize,
        w: usize,
        cy: f64,
        cx: f64,
        ry: f64,
        rx: f64,
    ) -> ndarray::Array2<bool> {
        let mut mask = ndarray::Array2::<bool>::from_elem((h, w), false);
        for y in 0..h {
            for x in 0..w {
                let dy = y as f64 - cy;
                let dx = x as f64 - cx;
                if (dy * dy) / (ry * ry) + (dx * dx) / (rx * rx) <= 1.0 {
                    mask[[y, x]] = true;
                }
            }
        }
        mask
    }

    #[test]
    fn hu_moments_are_nonzero_for_ellipse() {
        // Regression test for audit finding A04: the previous implementation
        // mirrored the Python `moments_normalized(binary_mask)` call pattern,
        // which treats pixels as moments and yields NaN -> 0.0 for all seven
        // Hu moments on modern scikit-image.
        let mask = ellipse_mask(120, 120, 60.0, 60.0, 40.0, 25.0);
        let area = mask.iter().filter(|&&v| v).count() as f64;
        assert!(area > 10.0, "test ellipse too small: {area}");
        let hu = calculate_hu_moments(&mask.view(), area).unwrap();
        assert!(
            hu["hu_moment_1"] > 0.0,
            "hu_moment_1 should be > 0 for an ellipse, got {}",
            hu["hu_moment_1"]
        );
        for i in 1..=7 {
            let v = hu[&format!("hu_moment_{i}")];
            assert!(v.is_finite(), "hu_moment_{i} must be finite, got {v}");
        }
        // hu_moment_1 is a normalized-moment invariant; for this ellipse it is
        // approximately 0.16-0.20 (previously 0.0 for every nucleus).
        assert!(
            (0.10..0.30).contains(&hu["hu_moment_1"]),
            "hu_moment_1 out of expected ellipse range: {}",
            hu["hu_moment_1"]
        );
    }

    #[test]
    fn hu_moments_zero_for_empty_mask() {
        let empty = ndarray::Array2::<bool>::from_elem((20, 20), false);
        let hu = calculate_hu_moments(&empty.view(), 0.0).unwrap();
        for i in 1..=7 {
            assert_eq!(hu[&format!("hu_moment_{i}")], 0.0);
        }
    }
}

#[cfg(test)]
mod feature_schema_tests {
    use super::*;

    /// The documented 129-feature schema plus `nucleus_id` (130 keys), as
    /// produced by `extract_all_features_from_instance_map`. Sorted.
    /// This is the contract that downstream analysis (the paper's 129-feature
    /// tables) depends on. See feature math audit (A04-A07): Hu moments must be
    /// nonzero, H&E/CCSM names use the legacy-renamed convention.
    const EXPECTED_KEYS: &[&str] = &[
        "area",
        "aspect_ratio",
        "bending_energy",
        "centroid_col",
        "centroid_row",
        "circularity",
        "convex_area",
        "convexity",
        "distance_to_nearest_neighbor",
        "eccentricity",
        "equivalent_diameter",
        "euler_number",
        "extent",
        "fourier_descriptor_1",
        "fourier_descriptor_2",
        "fourier_descriptor_3",
        "fourier_descriptor_4",
        "fourier_descriptor_5",
        "fractal_dimension",
        "hu_moment_1",
        "hu_moment_2",
        "hu_moment_3",
        "hu_moment_4",
        "hu_moment_5",
        "hu_moment_6",
        "hu_moment_7",
        "major_axis_length",
        "minor_axis_length",
        "neis_irregularity_score",
        "neis_spectral_energy",
        "neis_spectral_peak_mode",
        "nucleus_id",
        "orientation",
        "perimeter",
        "roughness",
        "solidity",
        "post_norm_ccsm_condensed_area_ratio",
        "post_norm_ccsm_contrast",
        "post_norm_ccsm_correlation",
        "post_norm_ccsm_energy",
        "post_norm_ccsm_homogeneity",
        "post_norm_ccsm_mean_clump_area",
        "post_norm_ccsm_mean_clump_eccentricity",
        "post_norm_ccsm_mean_clump_solidity",
        "post_norm_ccsm_mean_dist_to_boundary",
        "post_norm_ccsm_mean_nnd",
        "post_norm_ccsm_num_clumps",
        "post_norm_entropy_intensity",
        "post_norm_glcm_ASM",
        "post_norm_glcm_contrast",
        "post_norm_glcm_correlation",
        "post_norm_glcm_dissimilarity",
        "post_norm_glcm_energy",
        "post_norm_glcm_homogeneity",
        "post_norm_he_ratio_H_to_E",
        "post_norm_hog_max",
        "post_norm_hog_mean",
        "post_norm_hog_min",
        "post_norm_hog_std",
        "post_norm_iqr_intensity",
        "post_norm_kurt_eosin",
        "post_norm_kurt_hematoxylin",
        "post_norm_kurtosis_intensity",
        "post_norm_lbp_entropy",
        "post_norm_lbp_mean",
        "post_norm_lbp_std",
        "post_norm_max_eosin",
        "post_norm_max_hematoxylin",
        "post_norm_max_intensity",
        "post_norm_mean_eosin",
        "post_norm_mean_hematoxylin",
        "post_norm_mean_intensity",
        "post_norm_median_intensity",
        "post_norm_min_eosin",
        "post_norm_min_hematoxylin",
        "post_norm_min_intensity",
        "post_norm_range_intensity",
        "post_norm_skew_eosin",
        "post_norm_skew_hematoxylin",
        "post_norm_skewness_intensity",
        "post_norm_std_eosin",
        "post_norm_std_hematoxylin",
        "post_norm_std_intensity",
        "pre_norm_ccsm_condensed_area_ratio",
        "pre_norm_ccsm_contrast",
        "pre_norm_ccsm_correlation",
        "pre_norm_ccsm_energy",
        "pre_norm_ccsm_homogeneity",
        "pre_norm_ccsm_mean_clump_area",
        "pre_norm_ccsm_mean_clump_eccentricity",
        "pre_norm_ccsm_mean_clump_solidity",
        "pre_norm_ccsm_mean_dist_to_boundary",
        "pre_norm_ccsm_mean_nnd",
        "pre_norm_ccsm_num_clumps",
        "pre_norm_entropy_intensity",
        "pre_norm_glcm_ASM",
        "pre_norm_glcm_contrast",
        "pre_norm_glcm_correlation",
        "pre_norm_glcm_dissimilarity",
        "pre_norm_glcm_energy",
        "pre_norm_glcm_homogeneity",
        "pre_norm_he_ratio_H_to_E",
        "pre_norm_hog_max",
        "pre_norm_hog_mean",
        "pre_norm_hog_min",
        "pre_norm_hog_std",
        "pre_norm_iqr_intensity",
        "pre_norm_kurt_eosin",
        "pre_norm_kurt_hematoxylin",
        "pre_norm_kurtosis_intensity",
        "pre_norm_lbp_entropy",
        "pre_norm_lbp_mean",
        "pre_norm_lbp_std",
        "pre_norm_max_eosin",
        "pre_norm_max_hematoxylin",
        "pre_norm_max_intensity",
        "pre_norm_mean_eosin",
        "pre_norm_mean_hematoxylin",
        "pre_norm_mean_intensity",
        "pre_norm_median_intensity",
        "pre_norm_min_eosin",
        "pre_norm_min_hematoxylin",
        "pre_norm_min_intensity",
        "pre_norm_range_intensity",
        "pre_norm_skew_eosin",
        "pre_norm_skew_hematoxylin",
        "pre_norm_skewness_intensity",
        "pre_norm_std_eosin",
        "pre_norm_std_hematoxylin",
        "pre_norm_std_intensity",
    ];

    fn synthetic_scene() -> (ndarray::Array3<u8>, ndarray::Array2<u32>) {
        let mut rgb = ndarray::Array3::<u8>::zeros((80, 80, 3));
        let mut map = ndarray::Array2::<u32>::zeros((80, 80));
        // Ellipse-ish nucleus 1 (nonzero Hu moments expected).
        for y in 30..50 {
            for x in 30..55 {
                rgb[[y, x, 0]] = 180;
                rgb[[y, x, 1]] = 120;
                rgb[[y, x, 2]] = 90;
                map[[y, x]] = 1;
            }
        }
        // Rectangle nucleus 2.
        for y in 60..75 {
            for x in 40..60 {
                rgb[[y, x, 0]] = 100;
                rgb[[y, x, 1]] = 160;
                rgb[[y, x, 2]] = 200;
                map[[y, x]] = 2;
            }
        }
        (rgb, map)
    }

    #[test]
    fn extraction_emits_exactly_the_129_feature_schema() {
        let (rgb, map) = synthetic_scene();
        let feats = extract_all_features_from_instance_map(
            &rgb.view(),
            &map.view(),
            false,
            FeatureSchema::Legacy,
        )
        .unwrap();
        assert_eq!(feats.len(), 2, "expected 2 nuclei");
        for features in &feats {
            let mut keys: Vec<&String> = features.keys().collect();
            keys.sort();
            let keys: Vec<&str> = keys.into_iter().map(|s| s.as_str()).collect();
            let mut expected: Vec<&str> = EXPECTED_KEYS.to_vec();
            expected.sort();
            assert_eq!(
                keys,
                expected,
                "feature schema mismatch: got {} keys, expected {}",
                keys.len(),
                expected.len()
            );
            for (k, v) in features {
                assert!(v.is_finite(), "feature {k} is not finite: {v}");
            }
        }
    }

    #[test]
    fn hu_moments_are_nonzero_and_nnd_positive_in_full_pipeline() {
        // Regression for audit finding A04 at the full-pipeline level:
        // hu_moment_* must not collapse to zero, and with two nuclei the
        // nearest-neighbor distance must be positive.
        let (rgb, map) = synthetic_scene();
        let feats = extract_all_features_from_instance_map(
            &rgb.view(),
            &map.view(),
            false,
            FeatureSchema::Legacy,
        )
        .unwrap();
        for features in &feats {
            let hu1 = features["hu_moment_1"];
            assert!(
                hu1 > 0.0,
                "hu_moment_1 should be > 0 for a real nucleus, got {hu1}"
            );
            assert!(
                features["distance_to_nearest_neighbor"] > 0.0,
                "distance_to_nearest_neighbor should be positive with 2 nuclei"
            );
        }
    }
}

#[cfg(test)]
mod raw_feature_schema_tests {
    use super::*;

    #[test]
    fn legacy_pre_and_post_patch_features_are_identical() {
        let rgb = Array3::<u8>::from_shape_fn((16, 16, 3), |(row, col, channel)| {
            ((row * 17 + col * 11 + channel * 37) % 256) as u8
        });
        let mask = Array2::<bool>::from_shape_fn((16, 16), |(row, col)| {
            (3..13).contains(&row) && (4..12).contains(&col)
        });

        let raw = compute_patch_features(&rgb.view(), &mask.view(), false).unwrap();
        let mut schema = HashMap::new();
        extend_legacy_patch_features(&mut schema, &raw, &raw);

        assert_eq!(schema.len(), raw.len() * 2);
        for key in raw.keys() {
            let canonical = canonical_feature_name(key);
            assert_eq!(
                schema.get(&format!("pre_norm_{canonical}")),
                schema.get(&format!("post_norm_{canonical}"))
            );
        }
    }

    #[test]
    fn enabled_normalization_produces_distinct_post_features() {
        let rgb = Array3::<u8>::from_shape_fn((20, 20, 3), |(row, col, channel)| {
            (35 + (row * 7 + col * 11 + channel * 47) % 190) as u8
        });
        let mask = Array2::<bool>::from_shape_fn((20, 20), |(row, col)| {
            (3..17).contains(&row) && (3..17).contains(&col)
        });
        let normalized = stain_norm::normalize_staining_default(&rgb.view()).unwrap();
        let (pre, post) =
            compute_pre_post_patch_features(&rgb.view(), &normalized.view(), &mask.view(), false)
                .unwrap();
        assert_eq!(pre.len(), post.len());
        assert!(pre.iter().any(|(key, value)| {
            post.get(key)
                .is_some_and(|post_value| (value - post_value).abs() > 1e-9)
        }));
    }

    #[test]
    fn complete_extraction_is_bitwise_reproducible() {
        let image = Array3::<u8>::from_shape_fn((64, 64, 3), |(row, col, channel)| {
            (20 + (row * 31 + col * 17 + channel * 53) % 220) as u8
        });
        let instance_map = Array2::<u32>::from_shape_fn((64, 64), |(row, col)| {
            let dy = (row as f64 - 32.0) / 17.0;
            let dx = (col as f64 - 32.0) / 23.0;
            u32::from(dy * dy + dx * dx <= 1.0)
        });
        let first = extract_all_features_from_instance_map(
            &image.view(),
            &instance_map.view(),
            false,
            FeatureSchema::Legacy,
        )
        .unwrap();
        let second = extract_all_features_from_instance_map(
            &image.view(),
            &instance_map.view(),
            false,
            FeatureSchema::Legacy,
        )
        .unwrap();
        assert_eq!(first, second);
        assert!(first[0].values().all(|value| value.is_finite()));
    }

    #[test]
    fn schemas_have_stable_column_counts_and_membership() {
        let image = Array3::<u8>::from_shape_fn((48, 48, 3), |(r, c, channel)| {
            ((r * 17 + c * 11 + channel * 37) % 256) as u8
        });
        let instance_map = Array2::<u32>::from_shape_fn((48, 48), |(r, c)| {
            if (12..36).contains(&r) && (10..38).contains(&c) {
                1
            } else {
                0
            }
        });
        let legacy = extract_all_features_from_instance_map(
            &image.view(),
            &instance_map.view(),
            false,
            FeatureSchema::Legacy,
        )
        .unwrap()
        .remove(0);
        let dual = extract_all_features_from_instance_map(
            &image.view(),
            &instance_map.view(),
            false,
            FeatureSchema::Dual,
        )
        .unwrap()
        .remove(0);
        let v2 = extract_all_features_from_instance_map(
            &image.view(),
            &instance_map.view(),
            false,
            FeatureSchema::V2,
        )
        .unwrap()
        .remove(0);

        assert_eq!(legacy.len(), 130);
        assert_eq!(dual.len(), 219);
        assert_eq!(v2.len(), 90);
        assert!(legacy["hu_moment_1"] > 0.0);
        assert!((legacy["hu_moment_1"] - dual["hu_moment_1"]).abs() < 1e-12);
        assert!((legacy["hu_moment_1"] - v2["v2_hu_moment_1"]).abs() < 1e-12);
        assert!(legacy.keys().all(|key| dual.contains_key(key)));
        assert!(v2
            .keys()
            .all(|key| key == "nucleus_id" || key.starts_with("v2_")));
        assert!(v2.keys().all(|key| dual.contains_key(key)));
    }
}
